language: perl
perl:
  - 5.16
  - 5.14
before_install:
  - cpanm Devel::Cover::Report::Coveralls || { cat ~/.cpanm/build.log ; false ; }
script: perl Build.PL && ./Build build && cover -test
after_success:
  - cover -report coveralls
